<?xml version="1.0"?>
<definitions name="Travel"
        targetNamespace="http://cs.nju.edu.cn/tcao4bpel/travel"
        xmlns:tns="http://cs.nju.edu.cn/tcao4bpel/travel"
        xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:user="http://user.webservices.cs.nju.edu.cn"
        xmlns:flight="http://flight.webservices.cs.nju.edu.cn"
        xmlns:hotel="http://hotel.webservices.cs.nju.edu.cn" 
        xmlns:common="http://xsd.webservices.cs.nju.edu.cn/xsd">



     <import namespace="http://flight.webservices.cs.nju.edu.cn" location="FlightService.wsdl"></import>

     
 
    <plnk:partnerLinkType name="Flight">
        <plnk:role name="FlightProvider" portType="flight:FlightServicePortType"/>
        
    </plnk:partnerLinkType> 

  
</definitions>